import FooterSection from "@/components/layouts/footer";
import "../styles/globals.css";

export const metadata = {
  title: "Arqai Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="font-tamil">
      <body>
        <main>{children}</main>
        <FooterSection />
      </body>
    </html>
  );
}
